export type ContractAudience = 'Cá nhân' | 'Doanh nghiệp';
export type ContractKind = 'contract' | 'bundle';

export interface ContractItem {
  id: number;
  title: string;
  description: string;
  category: string;
  audience: ContractAudience;
  kind: ContractKind;
  rating: number;
  views: string;
  downloads: string;
  viewsCount: number;
  downloadCount: number;
  oldPrice: number;
  price: number;
  hot?: boolean;
  featured?: boolean;
  verified?: boolean;
  fileType?: 'DOCX' | 'DOCX + PDF' | 'ZIP';
  pages?: number;
  language?: 'Tiếng Việt' | 'Song ngữ Việt - Anh';
  updatedAt?: string;
  tags?: string[];
}

export const contractCategories = [
  'Hợp Đồng Hot',
  'Hợp Đồng Dịch Vụ | Cung Cấp',
  'Hợp Đồng Lao Động | Nhân sự',
  'Hợp đồng Khoán | Giao khoán',
  'Hợp Đồng Thanh Lý | Chấm Dứt',
  'Hợp Đồng Uỷ Quyền | Đại Diện',
  'Hợp Đồng Công Nghệ | Phần Mềm',
  'Hợp Đồng Bản Quyền | Sáng Chế',
  'Hợp Đồng Bảo Mật | Dữ Liệu',
  'Hợp Đồng Quảng Cáo | Truyền Tin',
  'Hợp Đồng Tổ Chức | Sự Kiện',
  'Hợp Đồng Đầu Tư | Dự Án',
  'Hợp Đồng Mua Bán | Thương Mại',
  'Hợp Đồng Thuê | Cho Thuê',
  'Hợp Đồng Xây Dựng',
  'Hợp Đồng Vận Chuyển | Logistics',
  'Hợp Đồng Vay | Tài Chính',
  'Hợp Đồng Góp Vốn | Hợp Tác',
  'Hợp Đồng Bất Động Sản',
  'Hợp Đồng Giáo Dục | Đào Tạo',
  'Hợp Đồng Đại Lý | Phân Phối',
  'Hợp Đồng Xuất Nhập Khẩu',
  'Hợp Đồng Nhượng Quyền | Franchise',
  'Hợp Đồng Y Tế | Chăm Sóc',
  'Hợp Đồng Du Lịch | Lữ Hành',
  'Hợp Đồng Bảo Hiểm',
  'Hợp Đồng Nông Nghiệp',
  'Hợp Đồng Kinh Doanh Online',
];

const c = (
  id: number,
  title: string,
  category: string,
  audience: ContractAudience,
  rating: number,
  views: string,
  viewsCount: number,
  downloads: string,
  downloadCount: number,
  oldPrice: number,
  price: number,
  description: string,
  flags: Pick<ContractItem, 'hot' | 'featured' | 'verified'> = {},
  meta: Partial<Pick<ContractItem, 'fileType' | 'pages' | 'language' | 'updatedAt' | 'tags'>> = {},
): ContractItem => ({
  id,
  title,
  description,
  category,
  audience,
  kind: 'contract',
  rating,
  views,
  downloads,
  viewsCount,
  downloadCount,
  oldPrice,
  price,
  verified: true,
  fileType: 'DOCX',
  pages: 7 + (id % 9),
  language: 'Tiếng Việt',
  updatedAt: `${String((id % 27) + 1).padStart(2, '0')}/09/2026`,
  tags: [category, audience, 'mẫu hợp đồng', 'luật sư biên soạn'],
  ...flags,
  ...meta,
});

export const contracts: ContractItem[] = [
  c(1, 'Mẫu hợp đồng thuê phòng trọ - Mẫu word chuẩn 2026, Luật sư biên soạn', 'Hợp Đồng Thuê | Cho Thuê', 'Cá nhân', 4.7, '89.8K', 89800, '679', 679, 125000, 80000, 'Mẫu hợp đồng thuê phòng trọ đầy đủ điều khoản về tiền thuê, tiền cọc, bàn giao, quyền và nghĩa vụ của các bên.', { hot: true, featured: true }),
  c(2, 'Hợp đồng khoán việc - Mẫu word chuẩn 2026, Luật sư biên soạn', 'Hợp đồng Khoán | Giao khoán', 'Doanh nghiệp', 4.6, '77.4K', 77400, '585', 585, 125000, 80000, 'Mẫu hợp đồng giao khoán công việc, quy định rõ phạm vi công việc, tiến độ, nghiệm thu, thanh toán và trách nhiệm.', { hot: true }),
  c(3, 'Mẫu hợp đồng thuê nhà trọ - Mẫu word chuẩn 2026, Luật sư biên soạn', 'Hợp Đồng Thuê | Cho Thuê', 'Cá nhân', 4.9, '107.0K', 107000, '809', 809, 125000, 80000, 'Hợp đồng thuê nhà trọ có điều khoản bàn giao, tiền cọc, điện nước, sửa chữa, chấm dứt và xử lý vi phạm.', { hot: true, featured: true }),
  c(4, 'Hợp đồng mua bán hàng hóa - Mẫu word chuẩn 2026, Luật sư biên soạn', 'Hợp Đồng Mua Bán | Thương Mại', 'Doanh nghiệp', 4.9, '138.7K', 138700, '1.0K', 1019, 125000, 80000, 'Mẫu mua bán hàng hóa dùng cho doanh nghiệp, có quy định về giao nhận, chất lượng, thanh toán, phạt và bồi thường.', { hot: true, featured: true }),
  c(5, 'Hợp đồng mua bán xe ô tô mới [mẫu Word chuẩn + file hướng dẫn làm]', 'Hợp Đồng Mua Bán | Thương Mại', 'Cá nhân', 4.5, '75.0K', 75000, '567', 567, 125000, 80000, 'Mẫu hợp đồng mua bán ô tô với nội dung về tình trạng xe, giấy tờ, nghĩa vụ thuế phí và thủ tục sang tên.'),
  c(6, 'Mẫu hợp đồng lao động mới nhất 2026 chuẩn form Bộ Lao Động - Tải file doc/docx', 'Hợp Đồng Lao Động | Nhân sự', 'Doanh nghiệp', 4.7, '91.3K', 91300, '690', 690, 125000, 80000, 'Mẫu hợp đồng lao động cập nhật, bao gồm vị trí, thời hạn, mức lương, quyền lợi, bảo mật và chấm dứt hợp đồng.', { featured: true }),
  c(7, 'Mẫu hợp đồng thuê đất [bản File Word mới nhất 2026, Luật sư biên soạn]', 'Hợp Đồng Thuê | Cho Thuê', 'Cá nhân', 4.9, '109.9K', 109900, '831', 831, 125000, 80000, 'Hợp đồng thuê quyền sử dụng đất với quy định về mục đích thuê, thời hạn, giá thuê, bàn giao và xử lý vi phạm.', { featured: true }),
  c(8, 'Hợp đồng dịch vụ tư vấn doanh nghiệp - Mẫu chuẩn, có điều khoản bảo mật', 'Hợp Đồng Dịch Vụ | Cung Cấp', 'Doanh nghiệp', 4.8, '63.2K', 63200, '481', 481, 145000, 95000, 'Mẫu hợp đồng dịch vụ tư vấn chuyên nghiệp, phân định phạm vi, phí dịch vụ, bảo mật và trách nhiệm đầu ra.'),
  c(9, 'Hợp đồng bảo mật thông tin (NDA) song phương - Bản chuẩn doanh nghiệp', 'Hợp Đồng Bảo Mật | Dữ Liệu', 'Doanh nghiệp', 4.9, '121.6K', 121600, '910', 910, 160000, 99000, 'NDA song phương quy định thông tin mật, ngoại lệ, thời hạn bảo mật, chế tài và cơ chế xử lý khi vi phạm.', { hot: true }),
  c(10, 'Hợp đồng phát triển phần mềm theo yêu cầu - Mẫu đầy đủ nghiệm thu và bản quyền', 'Hợp Đồng Công Nghệ | Phần Mềm', 'Doanh nghiệp', 4.8, '84.4K', 84400, '644', 644, 180000, 120000, 'Mẫu hợp đồng phát triển phần mềm có milestone, SLA, nghiệm thu, thanh toán, sở hữu trí tuệ và bảo hành.'),
  c(11, 'Hợp đồng quảng cáo và truyền thông - Mẫu chuẩn cho Agency và khách hàng', 'Hợp Đồng Quảng Cáo | Truyền Tin', 'Doanh nghiệp', 4.7, '72.1K', 72100, '526', 526, 150000, 99000, 'Quy định rõ hạng mục truyền thông, KPI, ngân sách, nghiệm thu, bản quyền nội dung và trách nhiệm các bên.'),
  c(12, 'Biên bản thanh lý hợp đồng dịch vụ - Mẫu Word chuẩn pháp lý', 'Hợp Đồng Thanh Lý | Chấm Dứt', 'Doanh nghiệp', 4.6, '55.9K', 55900, '423', 423, 90000, 60000, 'Mẫu biên bản xác nhận nghĩa vụ đã hoàn thành, công nợ, bàn giao, cam kết và thời điểm chấm dứt hiệu lực.'),
  c(13, 'Hợp đồng ủy quyền quản lý tài sản - Mẫu cá nhân mới nhất', 'Hợp Đồng Uỷ Quyền | Đại Diện', 'Cá nhân', 4.7, '68.4K', 68400, '497', 497, 110000, 75000, 'Mẫu ủy quyền quản lý tài sản với phạm vi ủy quyền, thời hạn, nghĩa vụ báo cáo và giới hạn giao dịch.'),
  c(14, 'Hợp đồng tổ chức sự kiện - Mẫu chi tiết cho doanh nghiệp và agency', 'Hợp Đồng Tổ Chức | Sự Kiện', 'Doanh nghiệp', 4.8, '58.7K', 58700, '438', 438, 150000, 99000, 'Mẫu hợp đồng tổ chức sự kiện với kịch bản, tiến độ, nhà cung cấp, thanh toán, hủy sự kiện và bất khả kháng.'),
  c(15, 'Hợp đồng hợp tác đầu tư dự án - Mẫu phân chia lợi nhuận và kiểm soát rủi ro', 'Hợp Đồng Đầu Tư | Dự Án', 'Doanh nghiệp', 4.9, '99.1K', 99100, '728', 728, 220000, 150000, 'Mẫu hợp tác đầu tư quy định phần vốn, quyền quản trị, phân chia lợi nhuận, thoái vốn và xử lý tranh chấp.'),
  c(16, 'Hợp đồng thi công xây dựng nhà ở - Mẫu đầy đủ tiến độ và bảo hành', 'Hợp Đồng Xây Dựng', 'Cá nhân', 4.8, '87.5K', 87500, '653', 653, 190000, 129000, 'Mẫu hợp đồng thi công nhà ở với dự toán, vật tư, nghiệm thu từng giai đoạn, bảo hành và phạt chậm tiến độ.'),
  c(17, 'Hợp đồng vận chuyển hàng hóa - Mẫu cho doanh nghiệp logistics', 'Hợp Đồng Vận Chuyển | Logistics', 'Doanh nghiệp', 4.7, '61.8K', 61800, '466', 466, 135000, 89000, 'Quy định tuyến vận chuyển, thời gian, bảo quản hàng hóa, chứng từ, cước phí và bồi thường mất mát.'),
  c(18, 'Hợp đồng chuyển nhượng quyền tác giả - Mẫu về bản quyền nội dung', 'Hợp Đồng Bản Quyền | Sáng Chế', 'Cá nhân', 4.8, '49.7K', 49700, '369', 369, 140000, 90000, 'Mẫu chuyển nhượng quyền tác giả, quy định phạm vi quyền, lãnh thổ, thời hạn, thù lao và cam kết quyền sở hữu.'),
  c(19, 'Hợp đồng vay tiền cá nhân có tài sản bảo đảm - Mẫu mới nhất', 'Hợp Đồng Vay | Tài Chính', 'Cá nhân', 4.8, '88.2K', 88200, '702', 702, 120000, 79000, 'Mẫu vay tiền có điều khoản lãi suất, thời hạn, tài sản bảo đảm, xử lý nợ quá hạn và phương thức thanh toán.'),
  c(20, 'Hợp đồng góp vốn thành lập doanh nghiệp - Mẫu phân chia quyền biểu quyết', 'Hợp Đồng Góp Vốn | Hợp Tác', 'Doanh nghiệp', 4.9, '92.6K', 92600, '715', 715, 175000, 115000, 'Mẫu góp vốn quy định tỷ lệ sở hữu, thời hạn góp, quyền biểu quyết, chuyển nhượng phần vốn và trách nhiệm thành viên.'),
  c(21, 'Hợp đồng đặt cọc mua bán nhà đất - Mẫu hạn chế rủi ro tranh chấp', 'Hợp Đồng Bất Động Sản', 'Cá nhân', 4.9, '143.4K', 143400, '1.1K', 1120, 145000, 95000, 'Mẫu đặt cọc mua bán nhà đất có điều khoản pháp lý tài sản, xử lý cọc, thời hạn công chứng và nghĩa vụ thuế.', { hot: true }),
  c(22, 'Hợp đồng đào tạo nghề và cam kết làm việc - Mẫu dành cho doanh nghiệp', 'Hợp Đồng Giáo Dục | Đào Tạo', 'Doanh nghiệp', 4.6, '46.8K', 46800, '352', 352, 125000, 82000, 'Quy định chương trình đào tạo, chi phí, thời gian cam kết làm việc, hoàn trả chi phí và bảo mật.'),
  c(23, 'Hợp đồng đại lý phân phối độc quyền - Mẫu thương mại đầy đủ', 'Hợp Đồng Đại Lý | Phân Phối', 'Doanh nghiệp', 4.8, '73.9K', 73900, '557', 557, 170000, 110000, 'Mẫu đại lý độc quyền với khu vực phân phối, doanh số, chiết khấu, tồn kho, thương hiệu và chấm dứt.'),
  c(24, 'Hợp đồng xuất khẩu hàng hóa song ngữ Việt - Anh', 'Hợp Đồng Xuất Nhập Khẩu', 'Doanh nghiệp', 4.9, '86.1K', 86100, '625', 625, 220000, 145000, 'Mẫu hợp đồng xuất khẩu có Incoterms, thanh toán quốc tế, chứng từ, kiểm định, giao hàng và giải quyết tranh chấp.'),
  c(25, 'Hợp đồng thuê mặt bằng kinh doanh - Mẫu có điều khoản hoàn trả hiện trạng', 'Hợp Đồng Thuê | Cho Thuê', 'Doanh nghiệp', 4.8, '78.6K', 78600, '603', 603, 135000, 89000, 'Mẫu thuê mặt bằng quy định đặt cọc, sửa chữa, biển hiệu, chi phí vận hành, bàn giao và hoàn trả hiện trạng.'),
  c(26, 'Hợp đồng thử việc - Mẫu Word cập nhật quy định mới', 'Hợp Đồng Lao Động | Nhân sự', 'Doanh nghiệp', 4.7, '69.2K', 69200, '520', 520, 95000, 65000, 'Mẫu thử việc xác định công việc, thời gian thử việc, lương, đánh giá kết quả và xử lý khi không đạt yêu cầu.'),
  c(27, 'Hợp đồng gia công sản phẩm - Mẫu quy định nguyên vật liệu và nghiệm thu', 'Hợp đồng Khoán | Giao khoán', 'Doanh nghiệp', 4.7, '57.4K', 57400, '441', 441, 145000, 95000, 'Mẫu gia công sản phẩm với quy cách, nguyên liệu, hao hụt, nghiệm thu, quyền sở hữu và trách nhiệm chất lượng.'),
  c(28, 'Hợp đồng chuyển giao công nghệ - Mẫu chuyên sâu cho doanh nghiệp', 'Hợp Đồng Công Nghệ | Phần Mềm', 'Doanh nghiệp', 4.9, '64.5K', 64500, '479', 479, 250000, 165000, 'Mẫu chuyển giao công nghệ quy định phạm vi chuyển giao, đào tạo, hỗ trợ kỹ thuật, bảo mật và quyền sở hữu.'),
  c(29, 'Thỏa thuận bảo mật nhân viên - NDA nội bộ doanh nghiệp', 'Hợp Đồng Bảo Mật | Dữ Liệu', 'Doanh nghiệp', 4.8, '79.8K', 79800, '619', 619, 110000, 72000, 'Thỏa thuận NDA nội bộ về dữ liệu khách hàng, bí mật kinh doanh, tài sản trí tuệ và nghĩa vụ sau khi nghỉ việc.'),
  c(30, 'Hợp đồng chuyển nhượng cổ phần - Mẫu đầy đủ điều kiện thanh toán', 'Hợp Đồng Đầu Tư | Dự Án', 'Doanh nghiệp', 4.9, '97.4K', 97400, '741', 741, 210000, 139000, 'Mẫu chuyển nhượng cổ phần quy định giá, điều kiện hoàn tất, nghĩa vụ thuế, bảo đảm và quyền sau chuyển nhượng.'),
  c(31, 'Hợp đồng cho mượn tài sản - Mẫu đơn giản cho cá nhân', 'Hợp Đồng Dịch Vụ | Cung Cấp', 'Cá nhân', 4.5, '35.6K', 35600, '274', 274, 80000, 50000, 'Mẫu cho mượn tài sản quy định tình trạng bàn giao, thời gian sử dụng, bảo quản và trách nhiệm hoàn trả.'),
  c(32, 'Hợp đồng mua bán căn hộ chung cư - Mẫu tham khảo pháp lý', 'Hợp Đồng Bất Động Sản', 'Cá nhân', 4.8, '116.2K', 116200, '897', 897, 180000, 120000, 'Mẫu mua bán căn hộ có thông tin pháp lý dự án, diện tích, thanh toán, bàn giao, phí quản lý và bảo hành.', { featured: true }),
  c(33, 'Hợp đồng dịch vụ sửa chữa nhà ở - Mẫu nghiệm thu và bảo hành', 'Hợp Đồng Dịch Vụ | Cung Cấp', 'Cá nhân', 4.6, '42.7K', 42700, '318', 318, 95000, 62000, 'Mẫu dành cho cá nhân thuê đơn vị sửa chữa, quy định hạng mục, vật tư, tiến độ, nghiệm thu, bảo hành và bồi thường khi thi công sai.', {}, { tags: ['sửa chữa nhà', 'dịch vụ', 'nghiệm thu', 'bảo hành'] }),
  c(34, 'Hợp đồng cung cấp dịch vụ kế toán - Mẫu cho doanh nghiệp SME', 'Hợp Đồng Dịch Vụ | Cung Cấp', 'Doanh nghiệp', 4.8, '54.3K', 54300, '411', 411, 145000, 95000, 'Quy định phạm vi công việc kế toán, thời hạn cung cấp chứng từ, bảo mật số liệu, SLA và trách nhiệm khi chậm báo cáo.', { featured: true }, { tags: ['kế toán', 'dịch vụ doanh nghiệp', 'SLA', 'bảo mật'] }),
  c(35, 'Hợp đồng cộng tác viên bán hàng - Mẫu hoa hồng và bảo mật thông tin', 'Hợp Đồng Lao Động | Nhân sự', 'Cá nhân', 4.7, '66.1K', 66100, '512', 512, 105000, 69000, 'Mẫu cộng tác viên quy định chính sách hoa hồng, KPI, thời điểm đối soát, bảo mật dữ liệu khách hàng và xử lý đơn hoàn.', {}, { tags: ['cộng tác viên', 'CTV', 'hoa hồng', 'bán hàng'] }),
  c(36, 'Thỏa thuận làm việc từ xa (Remote Work) - Phụ lục hợp đồng lao động', 'Hợp Đồng Lao Động | Nhân sự', 'Doanh nghiệp', 4.8, '71.9K', 71900, '546', 546, 115000, 75000, 'Phụ lục quy định địa điểm làm việc từ xa, thời gian online, thiết bị, bảo mật, đánh giá hiệu suất và chi phí hỗ trợ.', { hot: true }, { tags: ['remote work', 'làm việc từ xa', 'phụ lục lao động'] }),
  c(37, 'Hợp đồng khoán sửa chữa căn hộ - Mẫu cho chủ nhà và đội thi công', 'Hợp đồng Khoán | Giao khoán', 'Cá nhân', 4.6, '39.4K', 39400, '296', 296, 110000, 72000, 'Mẫu giao khoán sửa chữa căn hộ theo khối lượng, vật tư, mốc thanh toán, nghiệm thu và trách nhiệm bảo vệ tài sản.', {}, { tags: ['khoán sửa chữa', 'căn hộ', 'thi công'] }),
  c(38, 'Hợp đồng giao khoán nhân công xây dựng - Mẫu nghiệm thu theo khối lượng', 'Hợp đồng Khoán | Giao khoán', 'Doanh nghiệp', 4.8, '82.5K', 82500, '634', 634, 155000, 99000, 'Mẫu giao khoán nhân công theo đơn giá, khối lượng thực tế, an toàn lao động, nghiệm thu và tiến độ công trường.', { featured: true }, { tags: ['giao khoán', 'nhân công', 'xây dựng', 'khối lượng'] }),
  c(39, 'Biên bản thanh lý hợp đồng thuê nhà - Mẫu xác nhận công nợ và hoàn cọc', 'Hợp Đồng Thanh Lý | Chấm Dứt', 'Cá nhân', 4.7, '59.8K', 59800, '455', 455, 85000, 55000, 'Biên bản thanh lý ghi nhận tình trạng bàn giao, công nợ điện nước, tiền cọc, tài sản kèm theo và thời điểm chấm dứt.', {}, { tags: ['thanh lý thuê nhà', 'hoàn cọc', 'bàn giao'] }),
  c(40, 'Thỏa thuận chấm dứt hợp đồng hợp tác kinh doanh - Mẫu doanh nghiệp', 'Hợp Đồng Thanh Lý | Chấm Dứt', 'Doanh nghiệp', 4.8, '51.2K', 51200, '392', 392, 125000, 82000, 'Mẫu chấm dứt BCC quy định xử lý tài sản, công nợ, quyền sở hữu trí tuệ, nghĩa vụ còn tồn tại và bảo mật sau chấm dứt.', {}, { tags: ['chấm dứt BCC', 'hợp tác kinh doanh', 'công nợ'] }),
  c(41, 'Giấy ủy quyền ký kết hợp đồng và giao dịch ngân hàng - Mẫu công ty', 'Hợp Đồng Uỷ Quyền | Đại Diện', 'Doanh nghiệp', 4.8, '74.6K', 74600, '574', 574, 105000, 69000, 'Mẫu ủy quyền cho người đại diện thực hiện ký kết, giao dịch ngân hàng, nhận hồ sơ và giới hạn giá trị giao dịch.', { featured: true }, { tags: ['ủy quyền công ty', 'giao dịch ngân hàng', 'ký hợp đồng'] }),
  c(42, 'Hợp đồng thiết kế website cho cá nhân kinh doanh - Mẫu bàn giao source code', 'Hợp Đồng Công Nghệ | Phần Mềm', 'Cá nhân', 4.7, '48.9K', 48900, '367', 367, 135000, 89000, 'Quy định phạm vi thiết kế, giao diện, chức năng, source code, hosting, bảo hành và quyền sử dụng hình ảnh.', {}, { tags: ['thiết kế website', 'source code', 'freelancer'] }),
  c(43, 'Hợp đồng cấp phép sử dụng phần mềm SaaS - Mẫu B2B song ngữ', 'Hợp Đồng Công Nghệ | Phần Mềm', 'Doanh nghiệp', 4.9, '91.2K', 91200, '688', 688, 245000, 165000, 'Mẫu SaaS quy định license, số lượng user, SLA, dữ liệu, bảo mật, uptime, phí thuê bao và giới hạn trách nhiệm.', { hot: true, featured: true }, { fileType: 'DOCX + PDF', language: 'Song ngữ Việt - Anh', pages: 22, tags: ['SaaS', 'software license', 'SLA', 'song ngữ'] }),
  c(44, 'Hợp đồng chuyển nhượng quyền sử dụng hình ảnh - Mẫu cho cá nhân/KOL', 'Hợp Đồng Bản Quyền | Sáng Chế', 'Cá nhân', 4.7, '43.8K', 43800, '329', 329, 120000, 79000, 'Mẫu quy định phạm vi sử dụng hình ảnh, nền tảng, thời hạn, lãnh thổ, thù lao và quyền thu hồi trong trường hợp vi phạm.', {}, { tags: ['quyền hình ảnh', 'KOL', 'bản quyền'] }),
  c(45, 'Hợp đồng chuyển giao quyền sở hữu nhãn hiệu - Mẫu doanh nghiệp', 'Hợp Đồng Bản Quyền | Sáng Chế', 'Doanh nghiệp', 4.9, '69.7K', 69700, '531', 531, 195000, 129000, 'Quy định đối tượng nhãn hiệu, hồ sơ chuyển giao, phí, thuế, cam kết quyền sở hữu và thủ tục đăng ký tại cơ quan nhà nước.', { featured: true }, { tags: ['nhãn hiệu', 'trademark', 'chuyển giao'] }),
  c(46, 'Cam kết bảo mật thông tin khách hàng - Mẫu dành cho cá nhân cung cấp dịch vụ', 'Hợp Đồng Bảo Mật | Dữ Liệu', 'Cá nhân', 4.6, '37.9K', 37900, '287', 287, 85000, 55000, 'Mẫu cam kết bảo mật dữ liệu khách hàng, tài khoản truy cập, thông tin kinh doanh và nghĩa vụ xóa dữ liệu sau khi hoàn tất dịch vụ.', {}, { tags: ['bảo mật khách hàng', 'dữ liệu cá nhân', 'NDA'] }),
  c(47, 'Thỏa thuận xử lý dữ liệu cá nhân (DPA) - Mẫu theo Nghị định 13', 'Hợp Đồng Bảo Mật | Dữ Liệu', 'Doanh nghiệp', 4.9, '104.8K', 104800, '803', 803, 210000, 139000, 'Mẫu DPA quy định vai trò bên kiểm soát/xử lý dữ liệu, mục đích, biện pháp bảo vệ, chuyển dữ liệu và xử lý sự cố.', { hot: true }, { tags: ['DPA', 'Nghị định 13', 'dữ liệu cá nhân', 'privacy'] }),
  c(48, 'Hợp đồng booking KOL/KOC - Mẫu cho chiến dịch mạng xã hội', 'Hợp Đồng Quảng Cáo | Truyền Tin', 'Cá nhân', 4.8, '85.6K', 85600, '655', 655, 135000, 89000, 'Mẫu booking quy định nội dung, lịch đăng, quyền duyệt, hashtag, exclusivity, chỉ số báo cáo và xử lý khi nội dung bị gỡ.', { hot: true }, { tags: ['KOL', 'KOC', 'booking', 'TikTok', 'social media'] }),
  c(49, 'Hợp đồng dịch vụ quảng cáo đa kênh - Mẫu Agency Performance', 'Hợp Đồng Quảng Cáo | Truyền Tin', 'Doanh nghiệp', 4.9, '93.7K', 93700, '716', 716, 175000, 115000, 'Mẫu performance marketing quy định ngân sách media, KPI, tracking, quyền truy cập tài khoản quảng cáo, báo cáo và nghiệm thu.', { featured: true }, { tags: ['agency', 'performance marketing', 'KPI', 'media'] }),
  c(50, 'Hợp đồng thuê MC/ca sĩ biểu diễn sự kiện - Mẫu cá nhân', 'Hợp Đồng Tổ Chức | Sự Kiện', 'Cá nhân', 4.6, '31.5K', 31500, '238', 238, 85000, 55000, 'Mẫu thuê nghệ sĩ/MC quy định lịch tập, thời lượng biểu diễn, cát-xê, yêu cầu kỹ thuật, hình ảnh và điều kiện hủy.', {}, { tags: ['MC', 'ca sĩ', 'sự kiện', 'biểu diễn'] }),
  c(51, 'Hợp đồng tổ chức hội nghị khách hàng - Mẫu trọn gói cho Agency', 'Hợp Đồng Tổ Chức | Sự Kiện', 'Doanh nghiệp', 4.8, '57.2K', 57200, '438', 438, 165000, 109000, 'Quy định scope công việc, venue, thiết bị, nhân sự, kịch bản, phương án dự phòng, nghiệm thu và điều kiện hủy.', {}, { tags: ['hội nghị', 'event agency', 'venue', 'kịch bản'] }),
  c(52, 'Thỏa thuận góp vốn đầu tư kinh doanh cá nhân - Mẫu phân chia lợi nhuận', 'Hợp Đồng Góp Vốn | Hợp Tác', 'Cá nhân', 4.7, '76.3K', 76300, '586', 586, 125000, 82000, 'Mẫu góp vốn giữa cá nhân quy định số vốn, thời điểm góp, quản lý dòng tiền, phân chia lợi nhuận, rút vốn và xử lý lỗ.', {}, { tags: ['góp vốn', 'hợp tác cá nhân', 'phân chia lợi nhuận'] }),
  c(53, 'Hợp đồng hợp tác kinh doanh (BCC) - Mẫu doanh nghiệp chuyên sâu', 'Hợp Đồng Góp Vốn | Hợp Tác', 'Doanh nghiệp', 4.9, '118.4K', 118400, '912', 912, 220000, 149000, 'Mẫu BCC quy định mục tiêu hợp tác, đóng góp nguồn lực, bộ máy điều hành, phân chia lợi nhuận, nghĩa vụ thuế và thoái vốn.', { hot: true, featured: true }, { fileType: 'DOCX + PDF', pages: 24, tags: ['BCC', 'hợp tác kinh doanh', 'góp vốn', 'thoái vốn'] }),
  c(54, 'Hợp đồng vay tiền không lãi suất giữa cá nhân - Mẫu có lịch trả nợ', 'Hợp Đồng Vay | Tài Chính', 'Cá nhân', 4.7, '97.1K', 97100, '752', 752, 95000, 62000, 'Mẫu vay không lãi có lịch thanh toán, phương thức chuyển tiền, xác nhận đã nhận tiền và xử lý vi phạm nghĩa vụ trả nợ.', { featured: true }, { tags: ['vay tiền', 'không lãi', 'lịch trả nợ'] }),
  c(55, 'Hợp đồng tín dụng nội bộ giữa công ty mẹ và công ty con - Mẫu doanh nghiệp', 'Hợp Đồng Vay | Tài Chính', 'Doanh nghiệp', 4.8, '45.2K', 45200, '342', 342, 185000, 125000, 'Mẫu tài trợ nội bộ quy định hạn mức, lãi suất, giải ngân, mục đích vốn, báo cáo sử dụng vốn và nghĩa vụ thuế liên quan.', {}, { tags: ['vay nội bộ', 'công ty mẹ', 'công ty con', 'tín dụng'] }),
  c(56, 'Hợp đồng đặt cọc thuê căn hộ - Mẫu cá nhân dễ sử dụng', 'Hợp Đồng Bất Động Sản', 'Cá nhân', 4.7, '72.8K', 72800, '559', 559, 90000, 59000, 'Mẫu đặt cọc thuê căn hộ quy định số tiền cọc, thời hạn ký hợp đồng chính, điều kiện hoàn/mất cọc và hiện trạng tài sản.', {}, { tags: ['đặt cọc', 'thuê căn hộ', 'bất động sản'] }),
  c(57, 'Hợp đồng môi giới bất động sản - Mẫu độc quyền cho sàn giao dịch', 'Hợp Đồng Bất Động Sản', 'Doanh nghiệp', 4.8, '88.7K', 88700, '681', 681, 155000, 99000, 'Quy định phạm vi môi giới, phí môi giới, độc quyền, thông tin tài sản, nghĩa vụ hỗ trợ giao dịch và điều kiện thanh toán.', { featured: true }, { tags: ['môi giới bất động sản', 'độc quyền', 'sàn giao dịch'] }),
  c(58, 'Hợp đồng đào tạo kỹ năng cá nhân - Mẫu trung tâm và học viên', 'Hợp Đồng Giáo Dục | Đào Tạo', 'Cá nhân', 4.6, '36.8K', 36800, '279', 279, 85000, 55000, 'Mẫu ghi rõ chương trình, học phí, lịch học, bảo lưu, hoàn phí, quyền sử dụng hình ảnh và trách nhiệm của học viên.', {}, { tags: ['đào tạo', 'học viên', 'học phí', 'trung tâm'] }),
  c(59, 'Hợp đồng hợp tác đào tạo doanh nghiệp - Mẫu B2B', 'Hợp Đồng Giáo Dục | Đào Tạo', 'Doanh nghiệp', 4.8, '52.1K', 52100, '396', 396, 145000, 95000, 'Quy định chương trình, số lượng học viên, giảng viên, tài liệu, tiêu chí nghiệm thu, bảo mật và xuất hóa đơn.', {}, { tags: ['đào tạo doanh nghiệp', 'B2B', 'nghiệm thu'] }),
  c(60, 'Hợp đồng đại lý bán hàng cá nhân - Mẫu hoa hồng theo doanh số', 'Hợp Đồng Đại Lý | Phân Phối', 'Cá nhân', 4.5, '29.7K', 29700, '225', 225, 80000, 52000, 'Mẫu đại lý cá nhân quy định khu vực bán hàng, mức chiết khấu, chỉ tiêu, chính sách đổi trả và sử dụng thương hiệu.', {}, { tags: ['đại lý', 'hoa hồng', 'doanh số'] }),
  c(61, 'Hợp đồng phân phối sản phẩm toàn quốc - Mẫu nhà sản xuất và nhà phân phối', 'Hợp Đồng Đại Lý | Phân Phối', 'Doanh nghiệp', 4.9, '102.6K', 102600, '789', 789, 205000, 135000, 'Mẫu phân phối quy định vùng lãnh thổ, mức tồn kho, doanh số tối thiểu, chiết khấu, marketing, bảo hành và chấm dứt.', { hot: true }, { tags: ['phân phối', 'toàn quốc', 'doanh số', 'chiết khấu'] }),
  c(62, 'Hợp đồng mua bán hàng nhập khẩu - Mẫu giao dịch cá nhân có chứng từ', 'Hợp Đồng Xuất Nhập Khẩu', 'Cá nhân', 4.5, '27.4K', 27400, '206', 206, 105000, 69000, 'Mẫu giao dịch hàng nhập khẩu có thông tin xuất xứ, chứng từ, bảo hành, thuế phí và trách nhiệm khi hàng không đúng mô tả.', {}, { tags: ['hàng nhập khẩu', 'chứng từ', 'mua bán'] }),
  c(63, 'Hợp đồng nhập khẩu máy móc thiết bị - Song ngữ Việt - Anh', 'Hợp Đồng Xuất Nhập Khẩu', 'Doanh nghiệp', 4.9, '84.9K', 84900, '647', 647, 260000, 175000, 'Mẫu nhập khẩu máy móc quy định Incoterms, LC/TTR, chứng từ, lắp đặt, chạy thử, bảo hành và phạt giao hàng chậm.', { featured: true }, { fileType: 'DOCX + PDF', language: 'Song ngữ Việt - Anh', pages: 26, tags: ['import machinery', 'Incoterms', 'LC', 'song ngữ'] }),
  c(64, 'Hợp đồng nhượng quyền quán cà phê - Mẫu Franchise đầy đủ', 'Hợp Đồng Nhượng Quyền | Franchise', 'Cá nhân', 4.8, '71.4K', 71400, '541', 541, 195000, 129000, 'Mẫu franchise quy định phí nhượng quyền, royalty, nhận diện thương hiệu, đào tạo, nguyên liệu bắt buộc và kiểm soát chất lượng.', { hot: true }, { tags: ['franchise', 'nhượng quyền', 'quán cà phê', 'royalty'] }),
  c(65, 'Hợp đồng nhượng quyền thương mại chuỗi bán lẻ - Mẫu doanh nghiệp', 'Hợp Đồng Nhượng Quyền | Franchise', 'Doanh nghiệp', 4.9, '90.5K', 90500, '694', 694, 275000, 185000, 'Mẫu nhượng quyền chuỗi quy định territory, tiêu chuẩn vận hành, phí định kỳ, kiểm tra hệ thống, IP và điều kiện chuyển nhượng cửa hàng.', { featured: true }, { fileType: 'DOCX + PDF', pages: 28, tags: ['franchise chain', 'territory', 'royalty', 'IP'] }),
  c(66, 'Hợp đồng dịch vụ chăm sóc sức khỏe tại nhà - Mẫu cá nhân', 'Hợp Đồng Y Tế | Chăm Sóc', 'Cá nhân', 4.6, '22.8K', 22800, '173', 173, 90000, 59000, 'Mẫu dịch vụ chăm sóc tại nhà quy định lịch chăm sóc, phạm vi hỗ trợ, thông tin sức khỏe, bảo mật và tình huống khẩn cấp.', {}, { tags: ['chăm sóc tại nhà', 'y tế', 'bảo mật sức khỏe'] }),
  c(67, 'Hợp đồng cung cấp dịch vụ khám sức khỏe định kỳ - Mẫu doanh nghiệp', 'Hợp Đồng Y Tế | Chăm Sóc', 'Doanh nghiệp', 4.7, '34.6K', 34600, '263', 263, 150000, 99000, 'Quy định danh mục khám, số lượng nhân viên, lịch triển khai, dữ liệu sức khỏe, kết quả, nghiệm thu và thanh toán.', {}, { tags: ['khám sức khỏe', 'doanh nghiệp', 'dữ liệu sức khỏe'] }),
  c(68, 'Hợp đồng tour du lịch trọn gói - Mẫu khách hàng cá nhân', 'Hợp Đồng Du Lịch | Lữ Hành', 'Cá nhân', 4.7, '58.3K', 58300, '447', 447, 95000, 62000, 'Mẫu tour quy định lịch trình, dịch vụ bao gồm, chính sách đổi hủy, bảo hiểm, phụ thu và xử lý sự kiện bất khả kháng.', { featured: true }, { tags: ['tour du lịch', 'lữ hành', 'đổi hủy', 'bảo hiểm'] }),
  c(69, 'Hợp đồng tổ chức tour đoàn cho doanh nghiệp - Mẫu MICE', 'Hợp Đồng Du Lịch | Lữ Hành', 'Doanh nghiệp', 4.8, '41.9K', 41900, '319', 319, 145000, 95000, 'Mẫu tour MICE quy định số lượng khách, khách sạn, vận chuyển, gala, timeline, nghiệm thu và điều kiện thay đổi số lượng.', {}, { tags: ['MICE', 'tour đoàn', 'gala', 'doanh nghiệp'] }),
  c(70, 'Hợp đồng bảo hiểm tài sản cá nhân - Mẫu tham khảo điều khoản quyền lợi', 'Hợp Đồng Bảo Hiểm', 'Cá nhân', 4.5, '19.6K', 19600, '149', 149, 80000, 50000, 'Mẫu tham khảo cấu trúc hợp đồng bảo hiểm tài sản, phạm vi bảo hiểm, loại trừ, phí, thời hạn và thủ tục yêu cầu bồi thường.', {}, { tags: ['bảo hiểm tài sản', 'bồi thường', 'quyền lợi'] }),
  c(71, 'Hợp đồng bảo hiểm hàng hóa vận chuyển - Mẫu doanh nghiệp', 'Hợp Đồng Bảo Hiểm', 'Doanh nghiệp', 4.7, '33.8K', 33800, '258', 258, 140000, 92000, 'Quy định đối tượng bảo hiểm, hành trình, giá trị, điều kiện bảo hiểm, chứng từ tổn thất và thời hạn thông báo sự cố.', {}, { tags: ['cargo insurance', 'hàng hóa', 'vận chuyển', 'bồi thường'] }),
  c(72, 'Hợp đồng bao tiêu nông sản - Mẫu hộ kinh doanh và nông hộ', 'Hợp Đồng Nông Nghiệp', 'Cá nhân', 4.7, '46.2K', 46200, '354', 354, 105000, 69000, 'Mẫu bao tiêu quy định sản lượng, tiêu chuẩn chất lượng, giá thu mua, lịch giao nhận, vật tư hỗ trợ và xử lý khi mất mùa.', { featured: true }, { tags: ['bao tiêu nông sản', 'nông hộ', 'thu mua'] }),
  c(73, 'Hợp đồng liên kết sản xuất nông nghiệp - Mẫu doanh nghiệp và hợp tác xã', 'Hợp Đồng Nông Nghiệp', 'Doanh nghiệp', 4.8, '39.1K', 39100, '298', 298, 150000, 99000, 'Quy định vùng nguyên liệu, giống/vật tư, quy trình kỹ thuật, truy xuất nguồn gốc, bao tiêu và cơ chế chia sẻ rủi ro.', {}, { tags: ['liên kết sản xuất', 'hợp tác xã', 'truy xuất nguồn gốc'] }),
  c(74, 'Thỏa thuận bán hàng qua livestream - Mẫu cho cá nhân/KOC', 'Hợp Đồng Kinh Doanh Online', 'Cá nhân', 4.8, '92.3K', 92300, '708', 708, 115000, 75000, 'Mẫu thỏa thuận livestream quy định lịch phát, sản phẩm, hoa hồng, mã giảm giá, đối soát đơn, nội dung cấm và xử lý hoàn trả.', { hot: true }, { tags: ['livestream', 'KOC', 'TikTok Shop', 'hoa hồng'] }),
  c(75, 'Hợp đồng vận hành gian hàng sàn thương mại điện tử - Mẫu Agency', 'Hợp Đồng Kinh Doanh Online', 'Doanh nghiệp', 4.9, '87.6K', 87600, '673', 673, 185000, 125000, 'Mẫu vận hành gian hàng quy định phạm vi listing, ads, CSKH, dữ liệu, doanh số mục tiêu, quyền truy cập tài khoản và phí dịch vụ.', { featured: true }, { tags: ['Shopee', 'Lazada', 'TikTok Shop', 'ecommerce', 'agency'] }),
  c(76, 'Hợp đồng mua bán xe máy cũ - Mẫu cá nhân có biên bản bàn giao', 'Hợp Đồng Mua Bán | Thương Mại', 'Cá nhân', 4.6, '64.9K', 64900, '498', 498, 80000, 52000, 'Mẫu mua bán xe máy cũ ghi nhận hiện trạng, giấy tờ, giá, thời điểm bàn giao, trách nhiệm sang tên và khoản phạt chưa xử lý.', {}, { tags: ['xe máy cũ', 'mua bán', 'sang tên'] }),
  c(77, 'Hợp đồng cung ứng hàng hóa theo đơn đặt hàng - Mẫu doanh nghiệp', 'Hợp Đồng Mua Bán | Thương Mại', 'Doanh nghiệp', 4.8, '79.4K', 79400, '608', 608, 145000, 95000, 'Mẫu cung ứng dài hạn quy định PO, forecast, tiêu chuẩn chất lượng, giao hàng, nghiệm thu, công nợ và xử lý hàng lỗi.', {}, { tags: ['purchase order', 'PO', 'cung ứng', 'công nợ'] }),
  c(78, 'Hợp đồng thuê xe tự lái - Mẫu cá nhân có biên bản nhận xe', 'Hợp Đồng Thuê | Cho Thuê', 'Cá nhân', 4.7, '83.5K', 83500, '641', 641, 95000, 62000, 'Mẫu thuê xe quy định tiền cọc, giới hạn sử dụng, nhiên liệu, vi phạm giao thông, hư hỏng và biên bản nhận/trả xe.', { featured: true }, { tags: ['thuê xe', 'tự lái', 'biên bản nhận xe'] }),
  c(79, 'Hợp đồng thuê kho hàng - Mẫu doanh nghiệp có điều khoản PCCC', 'Hợp Đồng Thuê | Cho Thuê', 'Doanh nghiệp', 4.8, '62.7K', 62700, '479', 479, 145000, 95000, 'Mẫu thuê kho quy định diện tích, tải trọng, PCCC, an ninh, điện nước, bảo quản hàng, bàn giao và trách nhiệm khi xảy ra sự cố.', {}, { tags: ['thuê kho', 'PCCC', 'logistics', 'kho hàng'] }),
  c(80, 'Hợp đồng thi công nội thất văn phòng - Mẫu doanh nghiệp', 'Hợp Đồng Xây Dựng', 'Doanh nghiệp', 4.9, '68.8K', 68800, '526', 526, 195000, 129000, 'Mẫu thi công nội thất quy định bản vẽ, vật liệu, BOQ, tiến độ, nghiệm thu, bảo hành, an toàn và điều kiện làm việc tại tòa nhà.', { featured: true }, { tags: ['nội thất văn phòng', 'BOQ', 'thi công', 'bảo hành'] }),
];

const b = (
  id: number,
  title: string,
  description: string,
  category: string,
  rating: number,
  views: string,
  viewsCount: number,
  downloads: string,
  downloadCount: number,
  oldPrice: number,
  price: number,
): ContractItem => ({
  id,
  title,
  description,
  category,
  audience: 'Doanh nghiệp',
  kind: 'bundle',
  rating,
  views,
  downloads,
  viewsCount,
  downloadCount,
  oldPrice,
  price,
  verified: true,
  fileType: 'ZIP',
  pages: 80 + (id % 8) * 12,
  language: 'Tiếng Việt',
  updatedAt: `${String((id % 26) + 1).padStart(2, '0')}/09/2026`,
  tags: [category, 'gói hợp đồng', 'doanh nghiệp', 'bộ mẫu'],
});

export const bundles: ContractItem[] = [
  b(101, 'Gói 100 Hợp Đồng Doanh Nghiệp', 'Bao gồm 100 mẫu hợp đồng doanh nghiệp thường dùng nhất, được luật sư kiểm duyệt, tích hợp song ngữ và NDA, hỗ trợ vận hành và kiểm soát rủi ro tài chính.', 'Hợp Đồng Hot', 4.9, '95.0K', 95000, '115', 115, 8520000, 5990000),
  b(102, 'Gói 20 Hợp Đồng TMĐT & Marketing Online', 'Bao gồm 20 mẫu hợp đồng thường dùng nhất về thương mại điện tử và marketing online, áp dụng cho kinh doanh online và hợp tác quảng cáo.', 'Hợp Đồng Quảng Cáo | Truyền Tin', 4.9, '132.2K', 132200, '160', 160, 1840000, 1200000),
  b(103, 'Gói 20 Hợp Đồng Sản Xuất & Công Nghiệp', 'Bao gồm 20 mẫu hợp đồng thường dùng nhất về sản xuất và công nghiệp, áp dụng cho gia công, cung ứng và hợp tác sản xuất.', 'Hợp đồng Khoán | Giao khoán', 4.6, '79.0K', 79000, '95', 95, 1520000, 999000),
  b(104, 'Gói 20 Hợp Đồng Xuất Nhập Khẩu & Hải Quan', 'Bao gồm 20 mẫu hợp đồng thường dùng nhất về xuất nhập khẩu và hải quan, áp dụng cho ngoại thương, logistics và thông quan hàng hóa.', 'Hợp Đồng Xuất Nhập Khẩu', 4.8, '91.7K', 91700, '110', 110, 2170000, 1500000),
  b(105, 'Gói 20 Hợp Đồng Đầu Tư & Bất Động Sản', 'Bao gồm 20 mẫu hợp đồng thường dùng nhất về đầu tư và bất động sản, áp dụng cho mua bán, chuyển nhượng, cho thuê và hợp tác đầu tư.', 'Hợp Đồng Bất Động Sản', 4.9, '110.3K', 110300, '133', 133, 2400000, 1600000),
  b(106, 'Gói 20 Hợp Đồng Đầu Tư & Xây Dựng Chuyên Sâu', 'Bao gồm 20 mẫu hợp đồng thường dùng nhất về đầu tư và xây dựng chuyên sâu, áp dụng cho triển khai và quản lý dự án đầu tư xây dựng.', 'Hợp Đồng Xây Dựng', 4.5, '69.1K', 69100, '83', 83, 1690000, 999000),
  b(107, 'Gói 20 Hợp Đồng Thương Mại & Nhượng Quyền', 'Bao gồm 20 mẫu hợp đồng thường dùng nhất về thương mại và nhượng quyền, áp dụng cho mua bán, phân phối và hợp tác nhượng quyền.', 'Hợp Đồng Mua Bán | Thương Mại', 4.7, '81.7K', 81700, '98', 98, 1970000, 1300000),
  b(108, 'Gói 20 Hợp Đồng Công Nghệ & Phần Mềm', 'Bao gồm 20 mẫu hợp đồng thường dùng nhất về công nghệ và phần mềm, áp dụng cho phát triển, gia công và chuyển giao công nghệ.', 'Hợp Đồng Công Nghệ | Phần Mềm', 4.9, '94.3K', 94300, '114', 114, 1860000, 1300000),
  b(109, 'Gói 25 Hợp Đồng Nhân Sự & Lao Động', 'Bộ mẫu từ tuyển dụng, thử việc, lao động, đào tạo, bảo mật đến chấm dứt quan hệ lao động dành cho bộ phận HR.', 'Hợp Đồng Lao Động | Nhân sự', 4.8, '73.5K', 73500, '89', 89, 1750000, 1150000),
  b(110, 'Gói 15 Hợp Đồng Logistics & Vận Tải', 'Bộ hợp đồng vận chuyển, kho bãi, giao nhận, thuê xe và dịch vụ logistics có điều khoản bồi thường và bảo hiểm.', 'Hợp Đồng Vận Chuyển | Logistics', 4.7, '62.4K', 62400, '76', 76, 1450000, 950000),
  b(111, 'Gói 20 Hợp Đồng Agency & Dịch Vụ', 'Bộ hợp đồng dành cho agency và doanh nghiệp dịch vụ: tư vấn, thiết kế, marketing, sự kiện, bảo trì và nghiệm thu.', 'Hợp Đồng Dịch Vụ | Cung Cấp', 4.8, '70.8K', 70800, '86', 86, 1590000, 1050000),
  b(112, 'Gói 15 Hợp Đồng Startup & Gọi Vốn', 'Bộ hợp đồng góp vốn, đầu tư, cổ đông, bảo mật, chuyển nhượng cổ phần và hợp tác phát triển dành cho startup.', 'Hợp Đồng Đầu Tư | Dự Án', 4.9, '88.9K', 88900, '108', 108, 2100000, 1390000),
  b(113, 'Gói 25 Hợp Đồng Bất Động Sản & Cho Thuê', 'Bộ mẫu cho môi giới, chủ nhà và doanh nghiệp bất động sản: đặt cọc, mua bán, thuê, môi giới, quản lý tài sản và bàn giao.', 'Hợp Đồng Bất Động Sản', 4.9, '96.4K', 96400, '118', 118, 2350000, 1490000),
  b(114, 'Gói 18 Hợp Đồng Nhà Hàng & F&B', 'Bộ mẫu dành cho quán ăn, nhà hàng và chuỗi F&B: thuê mặt bằng, lao động, nhà cung cấp, KOL, nhượng quyền và tổ chức sự kiện.', 'Hợp Đồng Nhượng Quyền | Franchise', 4.8, '68.5K', 68500, '82', 82, 1680000, 1090000),
  b(115, 'Gói 20 Hợp Đồng Creator, KOL & Truyền Thông', 'Bộ mẫu booking KOL/KOC, cấp quyền hình ảnh, sản xuất nội dung, NDA, livestream, quảng cáo và quản lý kênh số.', 'Hợp Đồng Quảng Cáo | Truyền Tin', 4.9, '103.6K', 103600, '126', 126, 1890000, 1250000),
  b(116, 'Gói 30 Hợp Đồng Thương Mại Điện Tử', 'Bộ mẫu cho seller, brand và agency trên Shopee, Lazada, TikTok Shop: vận hành gian hàng, affiliate, livestream, logistics và dữ liệu.', 'Hợp Đồng Kinh Doanh Online', 4.9, '124.1K', 124100, '151', 151, 2490000, 1590000),
  b(117, 'Gói 20 Hợp Đồng Nhà Thầu & Xây Dựng', 'Bộ hợp đồng thi công, thiết kế, cung ứng vật tư, khoán nhân công, giám sát, nghiệm thu, thanh lý và bảo hành công trình.', 'Hợp Đồng Xây Dựng', 4.8, '85.7K', 85700, '104', 104, 1990000, 1290000),
  b(118, 'Gói 15 Hợp Đồng Giáo Dục & Trung Tâm Đào Tạo', 'Bộ mẫu cho trung tâm đào tạo: học viên, giảng viên, cộng tác viên, hợp tác B2B, bản quyền giáo trình và bảo mật.', 'Hợp Đồng Giáo Dục | Đào Tạo', 4.7, '55.9K', 55900, '68', 68, 1390000, 890000),
  b(119, 'Gói 15 Hợp Đồng Du Lịch & Sự Kiện MICE', 'Bộ mẫu tour, khách sạn, vận chuyển, gala, MC/ca sĩ, venue, agency và đối tác dịch vụ dành cho doanh nghiệp lữ hành.', 'Hợp Đồng Du Lịch | Lữ Hành', 4.8, '61.2K', 61200, '74', 74, 1480000, 950000),
  b(120, 'Gói 20 Hợp Đồng Nông Nghiệp & Chuỗi Cung Ứng', 'Bộ mẫu bao tiêu, liên kết sản xuất, cung ứng vật tư, thuê đất, vận chuyển, kho bãi, phân phối và truy xuất nguồn gốc.', 'Hợp Đồng Nông Nghiệp', 4.7, '48.6K', 48600, '59', 59, 1450000, 920000),
  b(121, 'Gói 25 Hợp Đồng Nhượng Quyền & Chuỗi Bán Lẻ', 'Bộ tài liệu cho mô hình franchise: nhượng quyền, thuê mặt bằng, nhà cung cấp, SOP, bảo mật, đại lý, phân phối và marketing.', 'Hợp Đồng Nhượng Quyền | Franchise', 4.9, '82.8K', 82800, '101', 101, 2290000, 1490000),
  b(122, 'Gói 18 Hợp Đồng Bảo Mật & Dữ Liệu Cá Nhân', 'Bộ mẫu NDA, DPA, chính sách xử lý dữ liệu, bảo mật nhân viên, nhà cung cấp, khách hàng và thỏa thuận chia sẻ dữ liệu.', 'Hợp Đồng Bảo Mật | Dữ Liệu', 4.9, '93.2K', 93200, '113', 113, 1980000, 1290000),
  b(123, 'Gói 20 Hợp Đồng Tài Chính & Gọi Vốn', 'Bộ mẫu vay, góp vốn, cổ đông, chuyển nhượng cổ phần, SAFE tham khảo, BCC và thỏa thuận đầu tư cho startup/doanh nghiệp.', 'Hợp Đồng Vay | Tài Chính', 4.9, '78.4K', 78400, '95', 95, 2250000, 1450000),
  b(124, 'Gói 15 Hợp Đồng Đại Lý & Phân Phối', 'Bộ mẫu đại lý, phân phối, ký gửi, rebate, chương trình bán hàng, hỗ trợ marketing và xử lý tồn kho dành cho doanh nghiệp.', 'Hợp Đồng Đại Lý | Phân Phối', 4.8, '64.7K', 64700, '79', 79, 1590000, 1020000),
];

export const team = [
  { name: 'Ls. Nguyễn Hùng', role: 'Nhà sáng lập / CEO', image: '/mau-hop-dong/team/LsNguyenHung.jpeg' },
  { name: 'Ls. Đặng Quý Tiên', role: 'Luật sư chuyên môn', image: '/mau-hop-dong/team/DangQuyTien.jpeg' },
  { name: 'Nguyễn Thành Tâm', role: 'Trưởng ban phát triển', image: '/mau-hop-dong/team/NguyenThanhTam.jpeg' },
  { name: 'Dương Quế Chi', role: 'Trưởng ban biên tập', image: '/mau-hop-dong/team/Chi.jpeg' },
  { name: 'Phan Thừa Ân', role: 'Biên tập viên', image: '/mau-hop-dong/team/PhanThuaAn.jpeg' },
  { name: 'Bùi Thị Ngọc Huyền', role: 'Biên tập viên', image: '/mau-hop-dong/team/BuiThiNgocHuyen.jpeg' },
  { name: 'Đỗ Minh Long', role: 'Biên tập viên', image: '/mau-hop-dong/team/DoMinhLong.jpeg' },
  { name: 'Lô Thị Thiên Nga', role: 'Biên tập viên', image: '/mau-hop-dong/team/LoThiThienNga.jpeg' },
  { name: 'Nguyễn Đăng Khuê', role: 'Biên tập viên', image: '/mau-hop-dong/team/NguyenDangKhuu.jpeg' },
  { name: 'Nguyễn Hoàng Lan Anh', role: 'Biên tập viên', image: '/mau-hop-dong/team/NguyenHoangLanAnh.jpeg' },
  { name: 'Nguyễn Tài Linh', role: 'Biên tập viên', image: '/mau-hop-dong/team/NguyenTaiLinh.jpeg' },
];

export const news = [
  { title: 'Hướng dẫn lập biên bản thanh lý hợp đồng du lịch chuẩn pháp lý', category: 'Luật pháp chung', date: '11/09/2025' },
  { title: 'Biên Bản Thanh Lý Hợp Đồng Chuyển Nhượng - Hướng Dẫn Chi Tiết & Mẫu Chuẩn', category: 'Luật pháp chung', date: '11/09/2025' },
  { title: 'Biên Bản Thanh Lý Hợp Đồng Chuyển Nhượng Vốn Góp - Hướng Dẫn Chi Tiết & Mẫu Chuẩn', category: 'Luật pháp chung', date: '11/09/2025' },
  { title: 'Hướng dẫn lập đơn xin ký hợp đồng lao động chuẩn pháp lý', category: 'Lao động - Nhân sự', date: '11/09/2025' },
  { title: 'Biên Bản Hợp Đồng Mua Bán Đất Là Gì? Mẫu & Hướng Dẫn Chi tiết (2025)', category: 'Bất động sản', date: '11/09/2025' },
  { title: '7 điều khoản bắt buộc nên có trong hợp đồng dịch vụ với Agency', category: 'Doanh nghiệp', date: '18/09/2026' },
  { title: 'Checklist rà soát hợp đồng thuê mặt bằng trước khi đặt cọc', category: 'Bất động sản', date: '21/09/2026' },
  { title: 'NDA và DPA khác nhau thế nào khi doanh nghiệp xử lý dữ liệu cá nhân?', category: 'Bảo mật dữ liệu', date: '25/09/2026' },
  { title: 'Incoterms 2020: chọn điều kiện giao hàng nào cho hợp đồng nhập khẩu?', category: 'Xuất nhập khẩu', date: '29/09/2026' },
  { title: 'Mẫu điều khoản nghiệm thu phần mềm giúp hạn chế tranh chấp dự án', category: 'Công nghệ', date: '02/10/2026' },
  { title: 'Hợp đồng KOL/KOC cần quy định gì về quyền sử dụng hình ảnh?', category: 'Marketing', date: '04/10/2026' },
];

export const formatVnd = (value: number) => new Intl.NumberFormat('vi-VN').format(value) + ' ₫';
