import type { AiProduct, CatalogCategory } from '../../ai-catalog/types';
export type { AiProduct, CatalogCategory, MarketplaceOffer } from '../../ai-catalog/types';

export const catalogTabs: Array<{ id: CatalogCategory; label: string; icon: string }> = [
  { id: 'all', label: 'Tất cả', icon: '✦' },
  { id: 'svod', label: 'SVOD', icon: '▶' },
  { id: 'ai', label: 'AI', icon: 'AI' },
  { id: 'music', label: 'Âm nhạc', icon: '♫' },
  { id: 'marketplace', label: 'Marketplace', icon: '▦' },
  { id: 'topup', label: 'Nạp tiền', icon: '+' },
  { id: 'software', label: 'Phần mềm', icon: '⌘' },
  { id: 'gaming', label: 'Trò chơi', icon: '◈' },
  { id: 'new', label: 'Mới', icon: '✧' },
];

export const products: AiProduct[] = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    category: 'ai',
    logo: '/assets/ai-accounts/chatgpt.webp',
    price: 125552,
    duration: '/ tháng',
    badge: '🖼️ ChatGPT Images 2.5',
    type: 'official',
    features: [
      'Các gói ChatGPT Plus với nhiều thời hạn đăng ký cùng tùy chọn riêng tư và dùng chung.',
      'GPT Images tạo hình ảnh nhanh, hỗ trợ chỉnh sửa và tinh chỉnh qua nhiều lượt trao đổi.',
      'Trò chuyện, viết nội dung, phân tích dữ liệu và tìm kiếm trên web trong một nơi.',
      'So sánh thời hạn và quyền truy cập trước khi chọn gói.',
    ],
  },
  {
    id: 'claude',
    name: 'Claude',
    category: 'ai',
    logo: '/assets/ai-accounts/claude.webp',
    price: 246946,
    type: 'marketplace',
    offerCount: 124,
    detailSlug: 'claude',
    tags: ['1 tháng', 'Tài khoản dùng chung', 'Toàn quyền truy cập', 'Max 5x'],
    offers: [
      { id: 'claude-1', title: 'Claude Pro | Tài khoản chia sẻ | Toàn cầu', price: 246946 },
      { id: 'claude-2', title: '1 Tháng Tài khoản Claude Pro | Mã kích hoạt', price: 259683 },
      { id: 'claude-3', title: 'Claude Pro | 1 Tháng | Giao hàng trong 20 phút', price: 286717 },
    ],
    features: [],
  },
  {
    id: 'suno',
    name: 'Suno',
    category: 'music',
    logo: '/assets/ai-accounts/suno.webp',
    price: 129711,
    duration: '/ tháng',
    type: 'official',
    joinedText: 'a5***25 đã tham gia 7 giờ trước',
    features: [
      'Gói Pro với thêm tín dụng để tạo nội dung chất lượng cao hơn.',
      'Nâng cấp giọng hát và hòa âm phối khí để tạo phong cách nhạc riêng.',
      '625 tín dụng mỗi người dùng mỗi tháng.',
      'Tối đa 10 công việc tạo nhạc chạy đồng thời.',
    ],
  },
  {
    id: 'cursor-market',
    name: 'Cursor',
    category: 'software',
    logo: '/assets/ai-accounts/cursor.webp',
    price: 779163,
    type: 'marketplace',
    offerCount: 50,
    detailSlug: 'cursor',
    tags: ['Pro+', '1 năm', 'Ultra', 'Enterprise', 'Nhóm'],
    offers: [
      { id: 'cursor-1', title: 'Cursor AI Pro - Tài khoản riêng tư, truy cập đầy đủ', price: 779163 },
      { id: 'cursor-2', title: 'Official Cursor Pro+ | Premium 1 Tháng', price: 2000260 },
      { id: 'cursor-3', title: 'Official Cursor Pro | Premium 1 Tháng', price: 883087 },
    ],
    features: [],
  },
  {
    id: 'replit',
    name: 'Replit',
    category: 'software',
    logo: '/assets/ai-accounts/replit.webp',
    price: 571874,
    type: 'marketplace',
    offerCount: 42,
    detailSlug: 'replit',
    tags: ['Core', '1 hồ sơ riêng tư', '3 tháng'],
    offers: [
      { id: 'replit-1', title: 'Replit Core Plan | 1 Tháng | $40 tín dụng AI', price: 571874 },
      { id: 'replit-2', title: 'Replit Core | Workspace lập trình AI và cloud', price: 1819600 },
      { id: 'replit-3', title: 'Replit Core | 1 Tháng | Truy cập đầy đủ', price: 389914 },
    ],
    features: [],
  },
  {
    id: 'higgsfield',
    name: 'Higgsfield',
    category: 'ai',
    logo: '/assets/ai-accounts/higgsfield.webp',
    price: 1013777,
    type: 'marketplace',
    offerCount: 39,
    detailSlug: 'higgsfield',
    tags: ['Plus', 'Gói cơ bản', '1 tháng'],
    offers: [
      { id: 'higgs-1', title: 'Higgsfield Pro | 1 Tháng | Truy cập đầy đủ', price: 1013777 },
      { id: 'higgs-2', title: 'Higgsfield Plus | 1200 credits | Seedance', price: 1117754 },
      { id: 'higgs-3', title: 'Higgsfield Basic | 180+ credits', price: 441903 },
    ],
    features: [],
  },
  {
    id: 'candy',
    name: 'Candy AI',
    category: 'ai',
    logo: '/assets/ai-accounts/candy.webp',
    price: 207694,
    duration: '/ tháng',
    type: 'official',
    joinedText: 'ya***50 đã tham gia 28 ngày trước',
    features: [
      'Gói Premium với thư viện nhân vật phong phú.',
      'Tạo người bạn đồng hành theo thiết lập riêng.',
      'Trò chuyện cá nhân hóa với hình ảnh và tin nhắn thoại.',
      'Xem rõ thời hạn và thông tin gói trước khi lựa chọn.',
    ],
  },
  {
    id: 'deepl',
    name: 'DeepL',
    category: 'software',
    logo: '/assets/ai-accounts/deepl.webp',
    price: 129711,
    type: 'marketplace',
    offerCount: 34,
    detailSlug: 'deepl',
    tags: ['Advanced', 'Write Pro', 'Private'],
    offers: [
      { id: 'deepl-1', title: 'DeepL Pro Advanced + Write Pro | 1 Tháng', price: 129711 },
      { id: 'deepl-2', title: 'DeepL | 3 Months | Full Access', price: 337666 },
      { id: 'deepl-3', title: 'DeepL Advanced | 1 Tháng | Tài khoản riêng', price: 178841 },
    ],
    features: [],
  },
  {
    id: 'grok',
    name: 'Grok',
    category: 'ai',
    logo: '/assets/ai-accounts/grok.webp',
    price: 389914,
    duration: '/ tháng',
    type: 'official',
    joinedText: 'hs***xa đã tham gia 15 giờ trước',
    features: [
      'Gói SuperGrok với tần suất truy vấn cao hơn.',
      'Khả năng lập trình, suy luận và thực thi nâng cao.',
      'Cửa sổ ngữ cảnh lớn hơn cho tác vụ phức tạp.',
      'Hỗ trợ tìm kiếm và suy luận theo quyền truy cập của gói.',
    ],
  },
  {
    id: 'cursor-official',
    name: 'Cursor',
    category: 'software',
    logo: '/assets/ai-accounts/cursor.webp',
    price: 467637,
    duration: '/ tháng',
    type: 'official',
    joinedText: 'ho***84 đã tham gia 14 giờ trước',
    features: [
      'Nhiều lựa chọn Pro và Pro+ linh hoạt.',
      'Phát hiện và sửa lỗi tự động trong quy trình lập trình.',
      'Hoàn thành mã không giới hạn.',
      'Proxy agent và luồng làm việc có thể mở rộng.',
    ],
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    category: 'ai',
    logo: '/assets/ai-accounts/perplexity.webp',
    price: 106316,
    duration: '/ tháng',
    type: 'official',
    joinedText: 'ki***ol đã tham gia 9 giờ trước',
    features: [
      'Công cụ tìm kiếm AI cung cấp câu trả lời trực tiếp.',
      'Hỏi đáp nhanh với nguồn tham khảo rõ ràng.',
      'Hỗ trợ nhiều tác vụ nghiên cứu và xử lý ngôn ngữ.',
    ],
  },
  {
    id: 'chatgpt-recharge',
    name: 'ChatGPT Recharge',
    category: 'ai',
    logo: '/assets/ai-accounts/chatgpt-recharge.webp',
    price: 714582,
    duration: '/ lần',
    badge: 'Nạp tiền vào tài khoản của bạn',
    type: 'official',
    features: [
      'Nạp Plus cho tài khoản ChatGPT cá nhân.',
      'Giữ lịch sử trò chuyện và dữ liệu riêng trên tài khoản của bạn.',
      'Xem thông tin quyền truy cập của gói trước khi đăng ký.',
      'Kiểm tra tài khoản nhận nâng cấp trước khi tiếp tục.',
    ],
  },
];

export const whyItems = [
  { icon: '⚡', title: 'Thời gian giao rõ ràng', description: 'So sánh thời gian giao dự kiến của từng ưu đãi ngay trong danh sách.' },
  { icon: '▦', title: 'Tất cả trong một nơi', description: 'Duyệt các dịch vụ AI, phần mềm và âm nhạc theo từng danh mục.' },
  { icon: '↓', title: 'Dễ dàng so sánh giá', description: 'Giá, thời hạn và quyền truy cập được trình bày cùng nhau để lựa chọn dễ hơn.' },
  { icon: '◉', title: 'Thông tin minh bạch', description: 'Xem người bán, đánh giá và thời gian bảo hành trước khi chọn ưu đãi.' },
  { icon: '24', title: 'Chọn theo nhu cầu', description: 'Lọc theo gói, thời lượng hoặc ngân sách để tìm lựa chọn phù hợp.' },
  { icon: '✓', title: 'Kiểm tra trước khi xác nhận', description: 'Đối chiếu thông tin gói và tổng tiền trong bước xác nhận.' },
];

export const reviews = [
  { name: 'iRead A Lot', country: 'SI', text: 'You can buy it with your local payment method, efficient customer service, perfect experience.' },
  { name: 'Janos', country: 'HU', text: 'I subscribed for a month without any issues and then extended it for another three months.' },
  { name: 'Emanuel Ciantar', country: 'MT', text: 'The service is reliable and the checkout flow is clear. Everything I need is visible in one place.' },
  { name: 'maxstei', country: 'DE', text: 'The interface makes it easy to compare plans and understand what is included before buying.' },
  { name: 'Gerard Gossier', country: 'FR', text: 'Service client réactif et efficace, expérience globale satisfaisante.' },
  { name: 'Anna Nowak', country: 'PL', text: 'Zawsze otrzymuję szybką i szczegółową pomoc. Interfejs jest przejrzysty i łatwy w użyciu.' },
  { name: 'Fernández', country: 'ES', text: 'Buena experiencia, con descuentos claros y un proceso de compra sencillo.' },
  { name: 'Tommaso Bonucci', country: 'IT', text: 'Una piattaforma semplice e conveniente con informazioni facili da capire.' },
];

export const faqs = [
  { question: 'Làm thế nào để chọn gói phù hợp?', answer: 'Chọn danh mục, mở danh sách ưu đãi và so sánh quyền truy cập, thời hạn, giá cùng thông tin người bán.' },
  { question: 'Gói đăng ký và Marketplace khác nhau thế nào?', answer: 'Card gói đăng ký giới thiệu quyền lợi chính của dịch vụ. Marketplace tập hợp các lựa chọn để so sánh theo gói và người bán.' },
  { question: 'Tôi có thể xem tất cả ưu đãi của một dịch vụ ở đâu?', answer: 'Chọn Xem tất cả trên card dịch vụ để mở danh sách ưu đãi tương ứng.' },
  { question: 'Làm sao tìm ưu đãi trong ngân sách?', answer: 'Nhập giá từ và giá đến trong bộ lọc; bạn cũng có thể sắp xếp theo giá thấp đến cao.' },
  { question: 'Có thể lọc theo thời hạn không?', answer: 'Chọn thời lượng ở bộ lọc bên trái danh sách. Trên điện thoại, mở Bộ lọc để xem các lựa chọn.' },
  { question: 'Toàn quyền truy cập nghĩa là gì?', answer: 'Đây là thuộc tính của ưu đãi. Hãy kiểm tra mô tả cụ thể về quyền sử dụng, tài khoản và phạm vi tính năng trước khi lựa chọn.' },
  { question: 'Tài khoản riêng và dùng chung khác nhau thế nào?', answer: 'Các hình thức có thể khác nhau về quyền quản lý, dữ liệu và số người sử dụng. Đối chiếu mô tả của từng gói trước khi tiếp tục.' },
  { question: 'Thời gian giao được hiển thị ở đâu?', answer: 'Thời gian giao dự kiến nằm ở cuối card ưu đãi. Dùng bộ lọc Giao hàng cam kết để tìm theo nhu cầu.' },
  { question: 'Tôi xem thông tin bảo hành ở đâu?', answer: 'Chọn nhãn bảo hành ở góc card ưu đãi để xem thông tin. Điều kiện cụ thể cần được xác nhận với người bán.' },
  { question: 'Làm sao so sánh người bán?', answer: 'Đối chiếu tên, điểm đánh giá, số phản hồi, giá và thời gian giao hiển thị trên từng card.' },
  { question: 'Tại sao không có kết quả sau khi lọc?', answer: 'Có thể chưa có ưu đãi đáp ứng đồng thời các điều kiện. Hãy mở rộng khoảng giá hoặc chọn Xóa bộ lọc.' },
  { question: 'Có thể xem các gói bằng điện thoại không?', answer: 'Vuốt ngang danh sách gói trong card hoặc các đánh giá. Nút chuyển cũng dùng được khi không thao tác vuốt.' },
  { question: 'Phiếu giảm giá được lưu như thế nào?', answer: 'Phiếu đã thu thập được ghi nhớ trong phiên duyệt hiện tại. Việc áp dụng vào đơn hàng cần hệ thống bán hàng kết nối đầy đủ.' },
  { question: 'Các thao tác mua hiện có tạo giao dịch không?', answer: 'Các gói và giá được lấy từ Medusa. Thao tác xác nhận hiện vẫn là bản xem trước, chưa tạo đơn hàng, thanh toán hoặc cấp tài khoản thực tế.' },
];
